# Site settings
title: All Things Anaïs
description: > # this means to ignore newlines until "baseurl:"
  
url: https://anais-seely.github.io
baseurl: /All-Things-Anais

disqus_shortname: kuoa # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
    external:     false
  - name:         Archive
    url:          /archive
    external:     false
  - name:         Youtube
    url:          https://www.youtube.com/c/AnaisSeely
    external:     true
-   name:         Instagram
    url:          https://www.instagram.com/anais.seely/?hl=en
    external:     true
    
# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
